from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt

TITULO = "RECIBO"
ALINHAMENTO_CENTRAL = WD_ALIGN_PARAGRAPH.CENTER
ALINHAMENTO_JUSTIFICADO = WD_ALIGN_PARAGRAPH.JUSTIFY
ALINHAMENTO_DIREITA = WD_ALIGN_PARAGRAPH.RIGHT
ESPACAMENTO_72 = Pt(72)
ESPACAMENTO_24 = Pt(24)
ESPACAMENTO_50 = Pt(50)
VALOR_FONT_SIZE = Pt(20)